# Generated by Django 4.1.2 on 2022-10-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carousel1', models.ImageField(upload_to='carousel1')),
                ('carousel2', models.ImageField(upload_to='carousel2')),
                ('carousel3', models.ImageField(upload_to='carousel3')),
                ('banner', models.ImageField(upload_to='banner')),
                ('logo', models.ImageField(upload_to='logo')),
                ('avatar', models.ImageField(upload_to='avatar')),
                ('copyright', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('pix', models.ImageField(upload_to='brandpix')),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='carpix')),
                ('registered', models.BooleanField()),
                ('uploaded_at', models.DateField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
